version: '3'
services:
  flask:
    build: .
    container_name: flask_app
    restart: always
    expose:
      - "5000"
    volumes:
      - ./webapp:/app

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - flask
